/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAssistant: typeof import('./src/components/AiAssistant.vue')['default']
    AppLoader: typeof import('./src/components/AppLoader.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppTooltip: typeof import('./src/components/AppTooltip.vue')['default']
    AssistantIcon: typeof import('./src/components/AssistantIcon.vue')['default']
    BreakupTable: typeof import('./src/components/monthlyMis/BreakupTable.vue')['default']
    BudgetActualsTab: typeof import('./src/components/foundationConsolidated/BudgetActualsTab.vue')['default']
    BudgetDrilldownModal: typeof import('./src/components/BudgetDrilldownModal.vue')['default']
    BudgetSummaryCards: typeof import('./src/components/BudgetSummaryCards.vue')['default']
    BudgetSummaryTable: typeof import('./src/components/BudgetSummaryTable.vue')['default']
    ChildTable: typeof import('./src/components/ChildTable.vue')['default']
    ColumnFilterDropdown: typeof import('./src/components/ColumnFilterDropdown.vue')['default']
    ConsolidatedTable: typeof import('./src/components/monthlyMis/ConsolidatedTable.vue')['default']
    CrCell: typeof import('./src/components/foundationConsolidated/CrCell.vue')['default']
    DynamicField: typeof import('./src/components/DynamicField.vue')['default']
    ExpenseTable: typeof import('./src/components/monthlyMis/ExpenseTable.vue')['default']
    ExpenseTreeTab: typeof import('./src/components/foundationConsolidated/ExpenseTreeTab.vue')['default']
    HeadcountTab: typeof import('./src/components/foundationConsolidated/HeadcountTab.vue')['default']
    InsightStrip: typeof import('./src/components/InsightStrip.vue')['default']
    MisAmount: typeof import('./src/components/monthlyMis/MisAmount.vue')['default']
    MobileNav: typeof import('./src/components/MobileNav.vue')['default']
    MobileShell: typeof import('./src/components/MobileShell.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PptTab: typeof import('./src/components/foundationConsolidated/PptTab.vue')['default']
    ProfileSettingsModal: typeof import('./src/components/ProfileSettingsModal.vue')['default']
    PwaUpdatePrompt: typeof import('./src/components/PwaUpdatePrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionLabel: typeof import('./src/components/SectionLabel.vue')['default']
    SettingsDoctypePanel: typeof import('./src/components/SettingsDoctypePanel.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
    SummaryInrTab: typeof import('./src/components/foundationConsolidated/SummaryInrTab.vue')['default']
    TopNavbar: typeof import('./src/components/TopNavbar.vue')['default']
    UnitDetailGrid: typeof import('./src/components/monthlyMis/UnitDetailGrid.vue')['default']
  }
}
